/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.apoteklatte.sisfo.ui;

import com.apoteklatte.sisfo.abstractmodel.table.AbsTableModelResepDetail;
import com.apoteklatte.sisfo.dao.impl.MasterObatDaoImpl;
import com.apoteklatte.sisfo.dao.impl.PasienDaoImpl;
import com.apoteklatte.sisfo.dao.impl.TransaksiDetailResepDaoImpl;
import com.apoteklatte.sisfo.dao.impl.TransaksiResepDaoImpl;
import com.apoteklatte.sisfo.model.ModelResepDetail;
import com.apoteklatte.sisfo.pojo.Dokter;
import com.apoteklatte.sisfo.pojo.MasterObat;
import com.apoteklatte.sisfo.pojo.Pasien;
import com.apoteklatte.sisfo.pojo.TransaksiDetailResep;
import com.apoteklatte.sisfo.pojo.TransaksiResep;
import com.apoteklatte.sisfo.utility.UtilityClass;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author FredillaPrima
 */
public class FormTransaksiResep extends javax.swing.JFrame {

    /**
     * Creates new form FormTransaksiResep
     */
    
    private LandingForm __landingForm;
    private FormDetailTransaksiResep __detail;
    private FormViewTransaksiResep __view;
    private int __mode; //0 baru - 1 edit
    
    private TransaksiResep __resep;
    private Dokter __dokter;
    private Pasien __pasien;
    
    private AbsTableModelResepDetail absTableModelResepDetail;
    private List<ModelResepDetail> listDetail;
    
    private TransaksiResepDaoImpl transaksiResepDaoImpl;
    private TransaksiDetailResepDaoImpl transaksiDetailResepDaoImpl;
    private MasterObatDaoImpl masterObatDaoImpl;
    private PasienDaoImpl pasienDaoImpl;

    public List<ModelResepDetail> getListDetail() {
        return listDetail;
    }

    public void setListDetail(List<ModelResepDetail> listDetail) {
        this.listDetail = listDetail;
    }

    public Dokter getDokter() {
        return __dokter;
    }

    public void setDokter(Dokter __dokter) {
        this.__dokter = __dokter;
    }
    
    public Pasien getPasien() {
        return __pasien;
    }

    public void setPasien(Pasien __pasien) {
        this.__pasien = __pasien;
    }
    
    public FormTransaksiResep(TransaksiResep resep, FormDetailTransaksiResep detail, FormViewTransaksiResep view, List<ModelResepDetail> listDetail, int mode) {
        initComponents();
        this.setLocationRelativeTo(this);
        __detail = detail;
        __view = view;
        __mode = mode;
        __resep = resep;
        setIcon();
        
        Date today = new Date();
        dcTglDibuat.setDate(today);
        
        absTableModelResepDetail = new AbsTableModelResepDetail();
        this.listDetail = listDetail;
        absTableModelResepDetail.setListDetail(listDetail);
        jTable1.setModel(absTableModelResepDetail);
        this.settingTableDetail();
        jTable1.invalidate();
        
        transaksiResepDaoImpl = new TransaksiResepDaoImpl();
        transaksiDetailResepDaoImpl = new TransaksiDetailResepDaoImpl();
        masterObatDaoImpl = new MasterObatDaoImpl();
        
        pasienDaoImpl = new PasienDaoImpl();
        
        dcTglDibuat.setDate(resep.getTglPembuatan());
        dcTgl.setDate(resep.getTglPengambilan());
        txtNoResep.setText(resep.getNoResep());
        txtKet.setText(resep.getKeterangan());
    }
    
    public FormTransaksiResep(LandingForm landingForm, int mode) {
        initComponents();
        this.setLocationRelativeTo(this);
        __landingForm = landingForm;
        __mode = mode;
        setIcon();
        
        Date today = new Date();
        dcTglDibuat.setDate(today);
        
        absTableModelResepDetail = new AbsTableModelResepDetail();
        listDetail = new ArrayList<ModelResepDetail>();
        absTableModelResepDetail.setListDetail(listDetail);
        jTable1.setModel(absTableModelResepDetail);
        this.settingTableDetail();
        jTable1.invalidate();
        
        transaksiResepDaoImpl = new TransaksiResepDaoImpl();
        transaksiDetailResepDaoImpl = new TransaksiDetailResepDaoImpl();
        masterObatDaoImpl = new MasterObatDaoImpl();
        
        pasienDaoImpl = new PasienDaoImpl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtNoIzin = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTelp = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtNamaPasien = new javax.swing.JTextField();
        txtUmur = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTgl = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dcTgl = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtKet = new javax.swing.JTextArea();
        dcTglDibuat = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        txtNoResep = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Transaksi Resep Dokter");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Transaksi Resep Dokter");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Dokter", 0, 0, new java.awt.Font("Arial", 1, 13))); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(440, 110));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Nama Dokter:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("No Ijin Praktek:");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton1.setText("Search Dokter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton2.setText("Clear Data");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtNoIzin.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtNoIzin.setText("no izin");
        txtNoIzin.setEnabled(false);

        txtNama.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtNama.setText("nama dokter");
        txtNama.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setText("No Telp:");

        txtTelp.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtTelp.setText("no telp");
        txtTelp.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(txtNoIzin)
                    .addComponent(txtTelp))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton2)
                    .addComponent(txtNoIzin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Pasien", 0, 0, new java.awt.Font("Arial", 1, 13))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(440, 142));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Nama Pasien:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Umur Pasien:");

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton3.setText("Search Pasien");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton4.setText("Clear Data");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txtNamaPasien.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtNamaPasien.setText("nama pasien");
        txtNamaPasien.setEnabled(false);

        txtUmur.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtUmur.setText("umur pasien");
        txtUmur.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setText("Tanggal Habis:");

        txtTgl.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtTgl.setText("tanggal habis obat terakhir");
        txtTgl.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(20, 20, 20)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNamaPasien, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(txtUmur)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTgl, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jButton3)
                    .addComponent(txtNamaPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jButton4)
                    .addComponent(txtUmur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Daftar Obat", 0, 0, new java.awt.Font("Arial", 1, 13))); // NOI18N

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton5.setText("Search Obat");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton6.setText("Delete Obat");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton7.setText("Clear Table");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Resep", 0, 0, new java.awt.Font("Arial", 1, 13))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Tanggal Dibuat:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("Tanggal Pengambilan:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("Keterangan:");

        dcTgl.setDateFormatString("dd / MM / yyyy");
        dcTgl.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        txtKet.setColumns(20);
        txtKet.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtKet.setRows(5);
        jScrollPane2.setViewportView(txtKet);

        dcTglDibuat.setDateFormatString("dd / MM / yyyy");
        dcTglDibuat.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("Nomor Resep:");

        txtNoResep.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dcTgl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dcTglDibuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNoResep)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(dcTglDibuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(dcTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNoResep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton8.setText("Back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton9.setText("Clear All Data");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton10.setText("Proses Resep");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(397, 397, 397)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (__detail == null) {
            this.setVisible(false);
            __landingForm.setVisible(true);
        } else {
            this.setVisible(false);
            __view.setVisible(true);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.clearDokter();
        JOptionPane.showMessageDialog(rootPane, "Data Dokter dibersihkan dari Form !");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        FormSearchDataDokter formSearchDataDokter = new FormSearchDataDokter(this);
        formSearchDataDokter.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.clearPasien();
        JOptionPane.showMessageDialog(rootPane, "Data Pasien dibersihkan dari Form !");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
        FormSearchDataPasien formSearchDataPasien = new FormSearchDataPasien(this);
        formSearchDataPasien.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int result = JOptionPane.showConfirmDialog(rootPane, "Apakah anda yakin untuk menghapus semua Data Resep Obat ?", "Hapus Data Resep Obat ", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            listDetail.removeAll(listDetail);
            this.refreshTableDetail();
            JOptionPane.showMessageDialog(rootPane, "Data Resep Obat dihapus dari table !");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int index = -1;
        index = jTable1.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(rootPane, "Pilih salah satu Data Resep Obat untuk dihapus !");
        } else {
            int result = JOptionPane.showConfirmDialog(rootPane, "Apakah anda yakin untuk menghapus Data Resep Obat ini?", "Hapus Data Obat Masuk", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                listDetail.remove(index);
                JOptionPane.showMessageDialog(rootPane, "Data Resep Obat berhasil dihapus dari tabel !");
                this.refreshTableDetail();
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.setVisible(false);
        FormSearchDataResepObat formSearchDataResepObat = new FormSearchDataResepObat(this);
        formSearchDataResepObat.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        txtKet.setText("");
        dcTgl.setDate(null);
        
        this.clearDokter();
        this.clearPasien();
        
        listDetail.removeAll(listDetail);
        this.refreshTableDetail();
        JOptionPane.showMessageDialog(rootPane, "Semua Data Transaksi Resep Obat dihapus dari Form !");
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if (__dokter == null || __pasien == null || listDetail.isEmpty() || dcTglDibuat.getDate() == null || txtNoResep.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Semua Data Transaksi Resep Dokter harus diisi !");
        } else if (__mode == 0) {
            //data baru
            int result = JOptionPane.showConfirmDialog(rootPane, "Apakah anda yakin untuk memproses Data Transaksi Resep Obat ini?", "Transaksi Resep Obat", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.OK_OPTION) {
                TransaksiResep resep = new TransaksiResep();
                resep.setDokter(__dokter);
                resep.setPasien(__pasien);
                resep.setKeterangan(txtKet.getText());
                resep.setTglPembuatan(dcTglDibuat.getDate());
                resep.setTglPengambilan(dcTgl.getDate());
                resep.setNoResep(txtNoResep.getText());
                transaksiResepDaoImpl.save(resep);

                Date tglObatHabis = null;
                boolean firstLoop = true;
                for (ModelResepDetail item : listDetail) {
                    TransaksiDetailResep detail = new TransaksiDetailResep();
                    detail.setObat(item.getObat());
                    detail.setKeterangan(item.getKeterangan());
                    detail.setQty(item.getQty());
                    detail.setSignaObat(item.getSignaObat());
                    detail.setSignaHari(item.getSignaHari());
                    detail.setTglObatHabis(item.getTglHabis());
                    detail.setTransaksiResep(resep);
                    transaksiDetailResepDaoImpl.save(detail);

                    MasterObat obat = item.getObat();
                    obat.setStokObat(obat.getStokObat() - detail.getQty());
                    masterObatDaoImpl.save(obat);

                    if (firstLoop) {
                        tglObatHabis = item.getTglHabis();
                        firstLoop = false;
                    }

                    if (tglObatHabis.before(item.getTglHabis())) {
                        tglObatHabis = item.getTglHabis();
                    }
                }

                Pasien pasien = __pasien;
                pasien.setLastTglObatHabis(tglObatHabis);
                pasienDaoImpl.save(pasien);

                JOptionPane.showMessageDialog(rootPane, "Data Transaksi Resep Obat berhasil disimpan !");

                txtKet.setText("");
                dcTgl.setDate(null);
                dcTglDibuat.setDate(new Date());

                this.clearDokter();
                this.clearPasien();

                listDetail.removeAll(listDetail);
                this.refreshTableDetail();
            }
        } else if (__mode == 1) {
            int result = JOptionPane.showConfirmDialog(rootPane, "Apakah anda yakin untuk meng-update Data Transaksi Resep Obat ini?", "Transaksi Resep Obat", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.OK_OPTION) {
                TransaksiResep resep = __resep;
                resep.setDokter(__dokter);
                resep.setPasien(__pasien);
                resep.setKeterangan(txtKet.getText());
                resep.setTglPembuatan(dcTglDibuat.getDate());
                resep.setTglPengambilan(dcTgl.getDate());
                resep.setNoResep(txtNoResep.getText());
                
                //kembalikan qty obat
                List<TransaksiDetailResep> listDeleted = transaksiDetailResepDaoImpl.getListDataByResep((int) __resep.getId());
                for (TransaksiDetailResep item : listDeleted) {
                    MasterObat obat = item.getObat();
                    obat.setStokObat(obat.getStokObat() + item.getQty());
                    masterObatDaoImpl.save(obat);
                }
                //hapus detail resep
                transaksiDetailResepDaoImpl.deleteData((int) __resep.getId());
                transaksiResepDaoImpl.save(resep);
                
                Date tglObatHabis = null;
                boolean firstLoop = true;
                for (ModelResepDetail item : listDetail) {
                    TransaksiDetailResep detail = new TransaksiDetailResep();
                    detail.setObat(item.getObat());
                    detail.setKeterangan(item.getKeterangan());
                    detail.setQty(item.getQty());
                    detail.setSignaObat(item.getSignaObat());
                    detail.setSignaHari(item.getSignaHari());
                    detail.setTglObatHabis(item.getTglHabis());
                    detail.setTransaksiResep(resep);
                    transaksiDetailResepDaoImpl.save(detail);

                    MasterObat obat = item.getObat();
                    obat.setStokObat(obat.getStokObat() - detail.getQty());
                    masterObatDaoImpl.save(obat);

                    if (firstLoop) {
                        tglObatHabis = item.getTglHabis();
                        firstLoop = false;
                    }

                    if (tglObatHabis.before(item.getTglHabis())) {
                        tglObatHabis = item.getTglHabis();
                    }
                }

                Pasien pasien = __pasien;
                pasien.setLastTglObatHabis(tglObatHabis);
                pasienDaoImpl.save(pasien);

                JOptionPane.showMessageDialog(rootPane, "Data Transaksi Resep Obat berhasil di-update !");

                txtKet.setText("");
                dcTgl.setDate(null);
                dcTglDibuat.setDate(new Date());

                this.clearDokter();
                this.clearPasien();

                listDetail.removeAll(listDetail);
                this.refreshTableDetail();
            }
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void clearDokter() {
        txtNama.setText("nama dokter");
        txtNoIzin.setText("no izin");
        txtTelp.setText("no telp");
        __dokter = null;
    }
    
    public void showDataDokter() {
        txtNama.setText(__dokter.getNamaDokter());
        txtNoIzin.setText(__dokter.getNoIzinPraktek());
        txtTelp.setText(__dokter.getNoTelp());
    }
    
    public void showDataPasien() {
        txtNamaPasien.setText(__pasien.getNamaPasien());
        txtUmur.setText(String.valueOf(__pasien.getUmurPasien()));
        if (__pasien.getLastTglObatHabis() != null) {
            txtTgl.setText(UtilityClass.formatDateToString(__pasien.getLastTglObatHabis()));
        } else {
            txtTgl.setText("");
        }
    }
    
    public void showDetailObat() {
        
    }
    
    private void clearPasien() {
        txtNamaPasien.setText("nama pasien");
        txtUmur.setText("umur pasien");
        txtTgl.setText("tanggal habis obat terakhir");
        __pasien = null;
    }
    
    private void settingTableDetail() {
        jTable1.getColumnModel().getColumn(0).setMaxWidth(150);
        jTable1.getColumnModel().getColumn(1).setMaxWidth(80);
        jTable1.getColumnModel().getColumn(2).setMaxWidth(40);
        jTable1.getColumnModel().getColumn(3).setMaxWidth(100);
        jTable1.getColumnModel().getColumn(4).setMaxWidth(150);
    }
    
    private void refreshTableDetail() {
        absTableModelResepDetail = new AbsTableModelResepDetail();
        absTableModelResepDetail.setListDetail(listDetail);
        jTable1.setModel(absTableModelResepDetail);
        this.settingTableDetail();
        jTable1.invalidate();
    }
    
    public void addDataResep (ModelResepDetail resep) {
        listDetail.add(resep);
        this.refreshTableDetail();
    }
    
    private void setIcon() {
        ClassLoader cl = this.getClass().getClassLoader();
        setIconImage(Toolkit.getDefaultToolkit().getImage(cl.getResource("pharmacy_icon.png")));
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FormTransaksiResep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FormTransaksiResep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FormTransaksiResep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FormTransaksiResep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FormTransaksiResep().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dcTgl;
    private com.toedter.calendar.JDateChooser dcTglDibuat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea txtKet;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNamaPasien;
    private javax.swing.JTextField txtNoIzin;
    private javax.swing.JTextField txtNoResep;
    private javax.swing.JTextField txtTelp;
    private javax.swing.JTextField txtTgl;
    private javax.swing.JTextField txtUmur;
    // End of variables declaration//GEN-END:variables
}
